### PR TITLE
Polaroid vignette, logo making of animation

### PR DESCRIPTION
**Pull request by gkaramanis**
Added the record_polaroid() vignette.
Added the animation file (logo-makingof.mp4) in man/figures, but no link in the README
I replaced the logo PNG with the one made with ggplot2

### CODE REVIEW

**Comment by thebioengineer** [comment]
Issue was that with the pkgdown yaml, we were specifying the vignettes. pkgdown complains and fails when there are vignettes that are not included in the yaml when we go through to specify them to prevent accidental omission.

**Comment by thebioengineer** [comment]
https://github.com/thebioengineer/camcorder/pull/41/files#diff-35fb157ec911e1a9f32e613a9dca5d6f0b07f53030fdf3de70fb0ea415954480 - for some reason the new logo is smaller than the original? @gkaramanis - is this the one you made programmatically? (also, would you mind sharing the final code to make the hex if so?)

**Comment by thebioengineer** [comment]
Oh, sorry, I wasn't referring to the number of pixels, in my preview of the logo, it looked like the hex wasn't as wide as it was in the original png...it's not a big deal.

**Comment by gkaramanis** [comment]
Oh, now I see what you mean, I clicked the link to the diff, sorry :)
It happened because of the black triangle that actually extends outside the hexagon. Now I have to fix it, but it may take some time to figure out how

**Comment by thebioengineer** [comment]
If you want to fix it, sure. But you can do it in another PR if you want

**Review by thebioengineer — APPROVED** [review]
I think this is good to merge into dev. And we can open another PR to merge updates to the logo once you get around to it an just make an issue for that.

**Comment by thebioengineer** [comment]
merging this in to keep it from hanging and I think its gtg. I'll open an issue to "resquare" the logo @gkaramanis

**Pull request merged**
