### PR TITLE
Image Resizing

### PR DESCRIPTION
**Pull request by thebioengineer**
- incorporate georgios' image resizing function (#1)
- add documentation
- set up to pass r cmd check

### CODE REVIEW

**Comment by thebioengineer** [comment]
Hey @Z3tt and @gkaramanis , could you review the new code I wrote to automatically apply the image resizing georgios wrote? I also added you two as contributors in the description file. Please check that out and let me know if the information is accurate.

Finally, I added a vignette and basically copied it into the readme.

**Review by gkaramanis — COMMENTED** [review]
I write a comment because I'm not sure how review works 😃

Firstly, great job! 👍 
I've done some tests, it works and looks pretty straightforward! 

I was just wondering about a thing with the size option in gg_playback(). When I choose a size over 600, the images get resized as expected but the gif is always 800x600

**Comment by thebioengineer** [comment]
> I write a comment because I'm not sure how review works 😃
> 
> Firstly, great job! 👍
> I've done some tests, it works and looks pretty straightforward!
> 
> I was just wondering about a thing with the size option in gg_playback(). When I choose a size over 600, the images get resized as expected but the gif is always 800x600

Thats a-okay to leave a comment, I wanted to make sure to have someone else review what I did! 

With the gif size, hmm, that must be a gifski thing, I'll take a look.

**Comment by thebioengineer** [comment]
Yupp - we can set it to be whatever we want. Should the height/width be the same as we set for the images?
```
gifski(png_files, gif_file = "animation.gif", width = 800, height = 600,
  delay = 1, loop = TRUE, progress = TRUE)
```

**Comment by gkaramanis** [comment]
Not sure about the height/width of the gif, it’s probably good to have a max size. But maybe show a warning/error if the user chooses a bigger size?

The issue with the gif (that I didn’t a very good job explaining) was that it was square when size < 600 but with size > 600 it got rectangular and distorted

**Comment by thebioengineer** [comment]
Gotcha! good point. I just added a bit of code that should make it so you only set `image_size`, and it will make a square. otherwise the user can decide the width/height if they want.

**Comment by gkaramanis** [comment]
Great! I’ll probably have more time to play with the package tomorrow, let me know if there’s anything you want me to test!

**Comment by thebioengineer** [comment]
A review of the readme, and we can look at reorganizing (and throwing some examples from both of you as the impetus of the package).  otherwise I would say this is good to go. We could submit to CRAN if you all want too

**Comment by gkaramanis** [comment]
The README looks good to me!

Just one small thing in this sentence (typo?):
Once the recorder is initialized, **the** go about making any plots

Are there any reasons for not having the package on CRAN? Otherwise, and if it's not too much work, I'm for!

**Comment by thebioengineer** [comment]
🤦 
it should be:
once the recorder is initialized, _then_ go about making any plots

oh, just wanted to make sure you both were on board with submitting!

**Pull request merged**
